# GNUmakefile.postamble

after-install::
	cp -r ../../Headers/ImageIO $(GNUSTEP_SYSTEM_HEADERS)/ImageIO
	cp ../../Headers/CoreGraphics/CGImageSource.h $(GNUSTEP_SYSTEM_HEADERS)/ImageIO
	cp ../../Headers/CoreGraphics/CGImageDestination.h $(GNUSTEP_SYSTEM_HEADERS)/ImageIO
